# Generated by Django 4.1.6 on 2023-03-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_phone_user_country_of_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client role'), ('STAFF', 'Staff role'), ('ADMIN', 'Administrator role')], max_length=6, verbose_name='role'),
        ),
    ]
