# Generated by Django 4.1.6 on 2023-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client role'), ('SPECIALIST', 'Data Entry Specialist role'), ('SUPERVISOR', 'Data Entry Supervisor role'), ('ADMIN', 'Admin role')], max_length=16, verbose_name='role'),
        ),
    ]
