# Generated by Django 4.1.6 on 2023-06-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('APPROVAL', 'Approval'), ('REJECTION', 'Rejection'), ('SUBMISSION', 'Submission'), ('SETTINGS', 'Settings')], max_length=16, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('detail', models.TextField(verbose_name='Detail')),
                ('read', models.BooleanField(default=False, verbose_name='Read Status (True means message has been read)')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
