# Generated by Django 4.1.6 on 2023-06-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_read_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('APPROVAL', 'Approval'), ('REJECTION', 'Rejection'), ('SUBMISSION', 'Submission'), ('PUBLISH', 'Publish'), ('SETTINGS', 'Settings')], max_length=16, verbose_name='Notification Type'),
        ),
    ]
