# Generated by Django 4.1.6 on 2023-08-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-updated_at',)},
        ),
    ]
