# Generated by Django 4.1.6 on 2023-06-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('detail', models.TextField(verbose_name='Detail')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVIEW', 'Review')], default='REVIEW', max_length=16, verbose_name='Status')),
                ('object_id', models.PositiveIntegerField()),
                ('reject_reason', models.TextField(verbose_name='Reason for rejection')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['content_type', 'object_id'], name='action_acti_content_59b007_idx'),
        ),
    ]
