# Generated by Django 4.1.6 on 2023-06-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_alter_action_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='reject_reason',
        ),
    ]
