# Generated by Django 4.1.6 on 2023-08-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_remove_action_reject_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('-updated_at',)},
        ),
    ]
