from .country import *
from .course import *
from .course_dates import *
from .currency import *
from .degree_type import *
from .discipline import *
from .language import *
from .programme_type import *
from .school import *