# Generated by Django 4.1.6 on 2023-03-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of country')),
                ('caption', models.TextField(verbose_name='Short caption')),
                ('continent', models.CharField(choices=[('AFRICA', 'AFRICA'), ('ASIA', 'ASIA'), ('EUROPE', 'EUROPE'), ('NORTH AMERICA', 'NORTH AMERICA'), ('SOUTH AMERICA', 'SOUTH AMERICA'), ('OCEANIA', 'OCEANIA')], max_length=16, verbose_name='Continent')),
                ('capital', models.CharField(max_length=125, verbose_name='Capital city')),
                ('population', models.IntegerField(verbose_name='Population of country')),
                ('students', models.IntegerField(blank=True, null=True, verbose_name='Total number of students in country')),
                ('international_students', models.IntegerField(blank=True, null=True, verbose_name='Total number of international students in country')),
                ('about', models.TextField(verbose_name='About')),
                ('about_wiki_link', models.URLField(verbose_name='Link to about on Wikipedia')),
                ('trivia_facts', models.TextField(blank=True, null=True, verbose_name='Trivia and fun facts')),
                ('living_costs', models.TextField(blank=True, null=True, verbose_name='Living costs essay')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date_year', models.IntegerField(blank=True, null=True, verbose_name='Start date year')),
                ('start_date_month', models.IntegerField(blank=True, null=True, verbose_name='Start date month')),
                ('application_deadline_year', models.IntegerField(blank=True, null=True, verbose_name='Application deadline year')),
                ('application_deadline_month', models.IntegerField(blank=True, null=True, verbose_name='Application deadline month')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of currency')),
                ('short_code', models.CharField(max_length=5, verbose_name='Short code of the currency')),
                ('usd_exchange_rate', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Exchange rate with the USD')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of discipline')),
                ('about', models.TextField(verbose_name='About')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of language')),
                ('iso_639_code', models.CharField(max_length=2, verbose_name='ISO 639 two-letter abbreviation')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgrammeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of programme type, e.g. Bachelors')),
                ('about', models.TextField(verbose_name='About')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of school')),
                ('about', models.TextField(verbose_name='About')),
                ('address', models.CharField(max_length=255, verbose_name='Address of school, including its country')),
                ('institution_type', models.CharField(blank=True, max_length=32, verbose_name='Institution type')),
                ('ranking', models.IntegerField(blank=True, null=True, verbose_name='THE WUR ranking')),
                ('year_established', models.IntegerField(blank=True, null=True, verbose_name='Year of establishment')),
                ('academic_staff', models.IntegerField(blank=True, null=True, verbose_name='Number of academic starr')),
                ('students', models.IntegerField(blank=True, null=True, verbose_name='Total number of students in the school')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_schools', to='academics.country')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DegreeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of degree type, e.g. Bachelor of Science')),
                ('short_name', models.CharField(max_length=255, verbose_name='Short name of degree type, e.g. B.Sc.')),
                ('programme_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_type_degree_types', to='academics.programmetype')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of school')),
                ('about', models.CharField(blank=True, max_length=1024, verbose_name='About')),
                ('overview', models.TextField(blank=True, verbose_name='Overview')),
                ('duration', models.IntegerField(blank=True, verbose_name='Duration (in months) of course')),
                ('tuition_fee', models.IntegerField(blank=True, null=True, verbose_name='Tuition fee')),
                ('tuition_fee_base', models.CharField(blank=True, max_length=16, verbose_name='Tuition fee base e.g. year, semester, full')),
                ('format', models.CharField(blank=True, choices=[('FULL', 'FULL TIME'), ('PART', 'PART TIME')], max_length=4, verbose_name='Course format')),
                ('attendance', models.CharField(blank=True, choices=[('SITE', 'ON SITE'), ('ONLINE', 'ONLINE'), ('BLENDED', 'BLENDED')], max_length=10, verbose_name='Course attendance format')),
                ('programme_structure', models.TextField(blank=True, verbose_name='Programme structure')),
                ('admission_requirements', models.TextField(blank=True, verbose_name='Admission requirements')),
                ('official_programme_website', models.URLField(blank=True, verbose_name='Official programme website')),
                ('course_dates', models.ManyToManyField(blank=True, related_name='course_dates_courses', to='academics.coursedates')),
                ('degree_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_type_courses', to='academics.degreetype')),
                ('disciplines', models.ManyToManyField(related_name='discipline_courses', to='academics.discipline')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_courses', to='academics.language')),
                ('programme_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_type_courses', to='academics.programmetype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_courses', to='academics.school')),
                ('tuition_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_courses', to='academics.currency')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_countries', to='academics.currency'),
        ),
    ]
