# Generated by Django 4.1.6 on 2023-03-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='format',
            new_name='course_format',
        ),
    ]
