# Generated by Django 4.1.6 on 2023-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_format_course_course_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='short_code',
            field=models.CharField(max_length=3, verbose_name='Short code of the currency (ISO 4217)'),
        ),
    ]
