# Generated by Django 4.1.6 on 2023-03-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_currency_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of course'),
        ),
    ]
