# Generated by Django 4.1.6 on 2023-03-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='academic_staff',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of academic staff'),
        ),
    ]
