# Generated by Django 4.1.6 on 2023-03-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_school_academic_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='short_code',
            field=models.CharField(default='ca', max_length=2, verbose_name='Short code of the country (ISO 3166-1 alpha-2)'),
            preserve_default=False,
        ),
    ]
