# Generated by Django 4.1.6 on 2023-05-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_course_author_course_published_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_dates',
        ),
        migrations.AddField(
            model_name='course',
            name='course_dates',
            field=models.JSONField(default={'deadline_month': 9, 'deadline_year': 2023, 'start_month': 6, 'start_year': 2024}),
            preserve_default=False,
        ),
    ]
