# Generated by Django 4.1.6 on 2023-05-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_dates',
            field=models.JSONField(null=True),
        ),
    ]
