# Generated by Django 4.1.6 on 2023-06-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_course_course_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='Reason for rejection'),
        ),
    ]
