# Generated by Django 4.1.6 on 2023-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_course_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published status of school'),
        ),
        migrations.AddField(
            model_name='school',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='Reason for rejection'),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW', 'REVIEW')], default='REVIEW', max_length=16, verbose_name='School status'),
        ),
    ]
