# Generated by Django 4.1.6 on 2023-06-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_currency_published_alter_country_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreetype',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published status of degree type'),
        ),
    ]
