# Generated by Django 4.1.6 on 2023-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_degreetype_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published status of discipline'),
        ),
    ]
