# Generated by Django 4.1.6 on 2023-06-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_discipline_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published status of language'),
        ),
    ]
