# Generated by Django 4.1.6 on 2023-06-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/academics/school/banners'),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(default='Lagos', max_length=255, verbose_name='City school is located'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/academics/school/logos'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address of school, excluding its city and country'),
        ),
    ]
