# Generated by Django 4.1.6 on 2023-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_country_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='color',
            field=models.CharField(blank=True, choices=[('deep_blue', 'Deep Blue'), ('green', 'Green'), ('orange', 'Orange'), ('yellow', 'yellow')], max_length=64, verbose_name='Icon color'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='icon',
            field=models.CharField(blank=True, max_length=64, verbose_name='Font Awesome 4.7 icon class name without the fa- part'),
        ),
    ]
