# Generated by Django 4.1.6 on 2023-06-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_rename_color_discipline_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmetype',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published status of programme type'),
        ),
    ]
