# Generated by Django 4.1.6 on 2023-06-09 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0029_programmetype_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.CreateModel(
            name='CourseDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of course')),
                ('about', models.CharField(blank=True, max_length=1024, verbose_name='About')),
                ('overview', models.TextField(blank=True, verbose_name='Overview')),
                ('duration', models.IntegerField(blank=True, verbose_name='Duration (in months) of course')),
                ('course_dates', models.JSONField(blank=True, null=True)),
                ('tuition_fee', models.IntegerField(blank=True, null=True, verbose_name='Tuition fee')),
                ('tuition_fee_base', models.CharField(blank=True, max_length=16, verbose_name='Tuition fee base e.g. year, semester, full')),
                ('course_format', models.CharField(blank=True, choices=[('FULL', 'FULL TIME'), ('PART', 'PART TIME')], max_length=4, verbose_name='Course format')),
                ('attendance', models.CharField(blank=True, choices=[('SITE', 'ON SITE'), ('ONLINE', 'ONLINE'), ('BLENDED', 'BLENDED')], max_length=10, verbose_name='Course attendance format')),
                ('programme_structure', models.TextField(blank=True, verbose_name='Programme structure')),
                ('admission_requirements', models.TextField(blank=True, verbose_name='Admission requirements')),
                ('official_programme_website', models.URLField(blank=True, verbose_name='Official programme website')),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW', 'REVIEW'), ('SAVED', 'SAVED')], default='SAVED', max_length=16, verbose_name='Course status')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Reason for rejection')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_draft_courses', to=settings.AUTH_USER_MODEL)),
                ('degree_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degree_type_draft_courses', to='academics.degreetype')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='discipline_draft_courses', to='academics.discipline')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_draft_courses', to='academics.language')),
                ('programme_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme_type_draft_courses', to='academics.programmetype')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_draft_courses', to='academics.school')),
                ('tuition_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_draft_courses', to='academics.currency')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_course', to='academics.coursedraft'),
        ),
    ]
