# Generated by Django 4.1.6 on 2023-06-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_remove_course_reject_reason_remove_course_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_course', to='academics.coursedraft'),
        ),
    ]
