# Generated by Django 4.1.6 on 2023-06-09 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0031_alter_course_course_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='school',
            name='status',
        ),
        migrations.AddField(
            model_name='school',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SchoolDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of school')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address of school, excluding its city and country')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City school is located')),
                ('institution_type', models.CharField(blank=True, max_length=32, verbose_name='Institution type')),
                ('ranking', models.IntegerField(blank=True, null=True, verbose_name='THE WUR ranking')),
                ('year_established', models.IntegerField(blank=True, null=True, verbose_name='Year of establishment')),
                ('academic_staff', models.IntegerField(blank=True, null=True, verbose_name='Number of academic staff')),
                ('students', models.IntegerField(blank=True, null=True, verbose_name='Total number of students in the school')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='uploads/academics/school/banners')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/academics/school/logos')),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW', 'REVIEW'), ('SAVED', 'SAVED')], default='SAVED', max_length=16, verbose_name='School status')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Reason for rejection')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_draft_schools', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_draft_schools', to='academics.country')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='school',
            name='school_draft',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_school', to='academics.schooldraft'),
            preserve_default=False,
        ),
    ]
