# Generated by Django 4.1.6 on 2023-06-09 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0032_remove_school_reject_reason_remove_school_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_countries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CountryDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of country')),
                ('short_code', models.CharField(blank=True, max_length=2, verbose_name='Short code of the country (ISO 3166-1 alpha-2)')),
                ('caption', models.TextField(blank=True, verbose_name='Short caption')),
                ('continent', models.CharField(blank=True, choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('OC', 'Oceania'), ('AN', 'Antarctica')], max_length=2, verbose_name='Continent')),
                ('capital', models.CharField(blank=True, max_length=125, verbose_name='Capital city')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Population of country')),
                ('students', models.IntegerField(blank=True, null=True, verbose_name='Total number of students in country')),
                ('international_students', models.IntegerField(blank=True, null=True, verbose_name='Total number of international students in country')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('about_wiki_link', models.URLField(blank=True, null=True, verbose_name='Link to about on Wikipedia')),
                ('trivia_facts', models.TextField(blank=True, verbose_name='Trivia and fun facts')),
                ('living_costs', models.TextField(blank=True, verbose_name='Living costs essay')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='uploads/academics/country/banners')),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW', 'REVIEW'), ('SAVED', 'SAVED')], default='SAVED', max_length=16, verbose_name='Country status')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_draft_countries', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_draft_countries', to='academics.currency')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='country',
            name='country_draft',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_country', to='academics.countrydraft'),
            preserve_default=False,
        ),
    ]
