# Generated by Django 4.1.6 on 2023-06-09 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0035_alter_currencydraft_short_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of discipline')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='Font Awesome 4.7 icon class name without the fa- part')),
                ('icon_color', models.CharField(blank=True, choices=[('deep_blue', 'Deep Blue'), ('green', 'Green'), ('orange', 'Orange'), ('yellow', 'yellow')], max_length=64, verbose_name='Icon color')),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW', 'REVIEW'), ('SAVED', 'SAVED')], default='SAVED', max_length=16, verbose_name='Discipline status')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_draft_discipline', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='discipline_draft',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_discipline', to='academics.disciplinedraft'),
            preserve_default=False,
        ),
    ]
