# Generated by Django 4.1.6 on 2023-06-15 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0038_currency_author_alter_currency_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_disciplines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplinedraft',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_draft_disciplines', to=settings.AUTH_USER_MODEL),
        ),
    ]
