# Generated by Django 4.1.6 on 2023-06-16 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0040_language_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreetype',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_degree_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
