# Generated by Django 4.1.6 on 2023-06-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0041_degreetype_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldraft',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_draft_schools', to='academics.country'),
        ),
    ]
