# Generated by Django 4.1.6 on 2023-07-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0042_alter_schooldraft_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_base',
            field=models.CharField(blank=True, choices=[('YEAR', 'YEAR'), ('MONTH', 'MONTH'), ('SESSION', 'SESSION'), ('SEMESTER', 'SEMESTER')], max_length=16, verbose_name='Course duration base (e.g. per year, month or semester)'),
        ),
        migrations.AddField(
            model_name='coursedraft',
            name='duration_base',
            field=models.CharField(blank=True, choices=[('YEAR', 'YEAR'), ('MONTH', 'MONTH'), ('SESSION', 'SESSION'), ('SEMESTER', 'SEMESTER')], max_length=16, verbose_name='Course duration base (e.g. per year, month or semester)'),
        ),
        migrations.AlterField(
            model_name='coursedraft',
            name='duration',
            field=models.IntegerField(blank=True, verbose_name='Duration of course'),
        ),
    ]
