# Generated by Django 4.1.6 on 2023-07-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0043_course_duration_base_coursedraft_duration_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tuition_fee_base',
            field=models.CharField(blank=True, choices=[('CREDIT', 'CREDIT'), ('SEMESTER', 'SEMESTER'), ('YEAR', 'YEAR'), ('PROGRAMME', 'FULL PROGRAMME')], max_length=16, verbose_name='Tuition fee base e.g. year, semester, full'),
        ),
        migrations.AlterField(
            model_name='coursedraft',
            name='tuition_fee_base',
            field=models.CharField(blank=True, choices=[('CREDIT', 'CREDIT'), ('SEMESTER', 'SEMESTER'), ('YEAR', 'YEAR'), ('PROGRAMME', 'FULL PROGRAMME')], max_length=16, verbose_name='Tuition fee base e.g. year, semester, full'),
        ),
    ]
