# Generated by Django 4.1.6 on 2023-08-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0044_alter_course_tuition_fee_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.CharField(blank=True, max_length=360124, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='coursedraft',
            name='about',
            field=models.CharField(blank=True, max_length=360124, verbose_name='About'),
        ),
    ]
