# Generated by Django 4.1.6 on 2023-08-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0045_alter_course_about_alter_coursedraft_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='usd_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Exchange rate with the USD'),
        ),
    ]
