# Generated by Django 4.1.6 on 2023-08-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0046_alter_currency_usd_exchange_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',)},
        ),
    ]
