# Generated by Django 4.1.6 on 2023-08-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0047_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='degreetype',
            options={'ordering': ('-programme_type', 'name')},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('name',)},
        ),
    ]
