# Generated by Django 4.1.6 on 2023-08-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0048_alter_currency_options_alter_degreetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmetype',
            options={'ordering': ('-id',)},
        ),
    ]
