# Generated by Django 4.1.6 on 2023-08-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0049_alter_programmetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydraft',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='coursedates',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='coursedraft',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='currencydraft',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='degreetypedraft',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='disciplinedraft',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='languagedraft',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='schooldraft',
            options={'ordering': ('-updated_at',)},
        ),
    ]
