# Generated by Django 4.1.6 on 2023-08-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0051_school_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Unique course slug (autogenerated)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Unique school slug (autogenerated)'),
        ),
    ]
