# Generated by Django 4.1.6 on 2023-08-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0053_alter_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Unique discipline slug (autogenerated)'),
        ),
    ]
