# Generated by Django 4.1.6 on 2023-08-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0054_discipline_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Unique discipline slug (autogenerated)'),
        ),
    ]
