# Generated by Django 4.1.6 on 2023-09-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0056_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='usd_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='Exchange rate with the USD'),
        ),
    ]
