# Generated by Django 4.1.6 on 2023-10-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0059_course_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured country?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured course?'),
        ),
    ]
